nav:
  Home: /
  Cryptocurrency / 数字货币: /categories/cryptocurrency
  Program Ape / 程序员: /categories/program-ape
  Finance / $$$$: /categories/finance
  Image Processing / 图像处理: /categories/image-processing
  Life Tips / 生活贴士: /categories/life-tips
  #Book Digest / 好书摘要: /categories/book-digest
  #Projects: http://github.com/ycshao

projects_url: http://github.com/ycshao

customize:
    gravatar:
        email:
    logo:
        enabled: true
        width: 70
        height: 70
        url: /images/logo.jpg
        gravatar: false
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/fandroid-chrome-144x144.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: http://github.com/ycshao
        twitter: https://twitter.com/ycshao
        facebook: https://www.facebook.com/ycshao0402
        linkedin: https://www.linkedin.com/in/ycshao
    post_count: 2000
    highlight: solarized-dark.styl

# RSS
rss: rss2.xml # I configured hexo-generator-feed to generate rss2.xml.

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-97811930-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
